name: Build

on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REHOSTING_ARC_REGISTRY || 'harbor.harbor.svc.cluster.local' }}
  USER: ${{ secrets.REHOSTING_ARC_REGISTRY_USER || 'external' }}
  CACHE: ${{ secrets.REHOSTING_ARC_REGISTRY && format('{0}/proxy', secrets.REHOSTING_ARC_REGISTRY) || 'docker.io' }}
  TARGET: ${{ secrets.REHOSTING_ARC_REGISTRY || 'harbor.harbor.svc.cluster.local/external' }}
  EXTERNAL_REGISTRY_PASS: 'PctyVGasz15Pn9M0yA9yMNwOawFaXnk3Tl4N'

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: rehosting-arc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from ${{ env.REGISTRY }}"
          openssl s_client -showcerts -connect ${{ env.REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ env.REGISTRY }}"]
              insecure = true
              http = true

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ secrets.REHOSTING_ARC_REGISTRY_PASSWORD || env.EXTERNAL_REGISTRY_PASS }}

      - name: Build QEMU package
        uses: docker/build-push-action@v6
        with:
          context: .
          target: package
          push: false
          tags: ${{ env.TARGET }}/rehosting/qemu:${{ github.sha }}
          build-args: |
            REGISTRY=${{ env.CACHE }}
          cache-from: |
            type=registry,ref=${{ env.TARGET }}/rehosting/qemu:cache,mode=max
            type=registry,ref=${{ env.TARGET }}/rehosting/qemu:cache-PR-${{ github.event.number }},mode=max
          cache-to: |
            type=registry,ref=${{ env.TARGET }}/rehosting/qemu:cache,mode=max
            type=registry,ref=${{ env.TARGET }}/rehosting/qemu:cache-PR-${{ github.event.number }}
